# require: rubocop-rake
AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  ExtraDetails: true
  NewCops: enable
  Exclude:
    - "_/**/*"
    - "spec/sample_input/**/*"
    - "spec/sample_output/**/*"
    - "lib/k_domain/raw_db_schema/template.rb"

Metrics/PerceivedComplexity:
  Exclude:
    - "lib/k_domain/domain_model/transform_steps/*.rb"
    - "lib/k_domain/domain_model/dtos/entity.rb"
    - "lib/k_domain/domain_model/dtos/old/entity.rb"

Metrics/AbcSize:
  Exclude:
    - "lib/k_domain/domain_model/transform_steps/*.rb"
    - "lib/k_domain/domain_model/dtos/rails_model.rb"
    - "lib/k_domain/domain_model/dtos/entity.rb"
    - "lib/k_domain/domain_model/dtos/column_old.rb"
    - "lib/k_domain/domain_model/dtos/old/column_old.rb"
    - "lib/k_domain/domain_model/dtos/old/rails_model.rb"
    - "lib/k_domain/domain_model/dtos/old/entity.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/k_domain/domain_model/transform_steps/*.rb"
    - "lib/k_domain/domain_model/dtos/entity.rb"
    - "lib/k_domain/domain_model/dtos/old/entity.rb"

Metrics/BlockLength:
  Exclude:
    - "**/spec/**/*"
    - "*.gemspec"
    - 'lib/k_domain/domain_model/dtos/erd_file.rb'    
  IgnoredMethods:
    - configure
    - context
    - define
    - describe
    - draw
    - factory
    - feature
    - guard
    - included
    - it
    - let
    - let!
    - scenario
    - setup
    - shared_context
    - shared_examples
    - shared_examples_for
    - transaction

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "lib/k_domain/domain_model/transform_steps/*.rb"
    - "lib/k_domain/domain_model/dtos/rails_model.rb"
    - "lib/k_domain/domain_model/dtos/old/entity.rb"
    - "lib/k_domain/domain_model/dtos/old/rails_model.rb"

Layout/LineLength:
  Max: 200
  # Ignores annotate output
  IgnoredPatterns: ['\A# \*\*']
  IgnoreCopDirectives: true
  Exclude:
    - "lib/k_domain/domain_model/transform_steps/*.rb"

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Style/BlockComments:
  Enabled: false
  Include:
    - "**/spec/*"

# My Preferences - Start
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Exclude:
    - "**/spec/**/*"
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/VariableNumber:
  Exclude:
    - "**/spec/**/*"
Style/EmptyMethod:    
  Exclude:
    - "**/spec/**/*"
Metrics/ParameterLists:
  Exclude:
    - "**/spec/**/*"
Layout/EmptyLineBetweenDefs:
  Exclude:
    - "**/spec/**/*"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "**/spec/**/*"

Style/AccessorGrouping:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: false
# My Preferences - End
